server:
 port: 8081

spring:
 application:
  name: ORDER-MANAGEMENT-SERVICE

#eureka:
 #client:
  #register-with-client: true
  #fetch-registery: true
  #service-url:
   #defaultZone: http://localhost:8761/eureka/
 #instance:
  #hostname: localhost 